
package turistickaagencija;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


/**
 *
 * @author Cira
 */
public class Agencija extends javax.swing.JFrame {

    /**
     * Creates new form Agencija
     */
    public Agencija() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    public void theQuery(String query){
        Connection conn = null;
        Statement  st = null;
        try {
            conn = DriverManager.getConnection("jdbc:mysql://localhost/agencija","root","cira");
            st= conn.createStatement();
            st.execute(query);
            JOptionPane.showMessageDialog(null,"Gost je uspesno dodat");
        }
        catch(Exception ex){
            JOptionPane.showConfirmDialog(null,ex.getMessage());
            
        }  
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        naslovpnl = new javax.swing.JPanel();
        naslovlbl = new javax.swing.JLabel();
        gostpnl = new javax.swing.JPanel();
        emaillbl = new javax.swing.JLabel();
        imelbl = new javax.swing.JLabel();
        prezimelbl = new javax.swing.JLabel();
        adresalbl = new javax.swing.JLabel();
        telefonlbl = new javax.swing.JLabel();
        emailfld = new javax.swing.JTextField();
        imefld = new javax.swing.JTextField();
        prezimefld = new javax.swing.JTextField();
        adresafld = new javax.swing.JTextField();
        telefonfld = new javax.swing.JTextField();
        dodajbtn = new javax.swing.JButton();
        detaljipnl = new javax.swing.JPanel();
        polazaklbl = new javax.swing.JLabel();
        polazaklbl1 = new javax.swing.JLabel();
        destinacijacbx = new javax.swing.JComboBox<>();
        polazakcbx = new javax.swing.JComboBox<>();
        prtljagbox = new javax.swing.JCheckBox();
        taksebox = new javax.swing.JCheckBox();
        osiguranjebox = new javax.swing.JCheckBox();
        detalji2 = new javax.swing.JPanel();
        letlbl = new javax.swing.JLabel();
        pklasarb = new javax.swing.JRadioButton();
        eklasarb = new javax.swing.JRadioButton();
        bklasarb = new javax.swing.JRadioButton();
        kartalbl = new javax.swing.JLabel();
        povratnarb = new javax.swing.JRadioButton();
        jednosmernarb = new javax.swing.JRadioButton();
        cenepnl = new javax.swing.JPanel();
        ukupnolbl = new javax.swing.JLabel();
        cenalbl = new javax.swing.JLabel();
        takselbl = new javax.swing.JLabel();
        cena3lbl = new javax.swing.JLabel();
        cena1lbl = new javax.swing.JLabel();
        cena2lbl = new javax.swing.JLabel();
        racunpnl = new javax.swing.JPanel();
        racunlbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        racunarea = new javax.swing.JTextArea();
        dugmadpnl = new javax.swing.JPanel();
        izlazbtn = new javax.swing.JButton();
        racunbtn = new javax.swing.JButton();
        ponistibtn = new javax.swing.JButton();
        ukupnobtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        naslovpnl.setBackground(new java.awt.Color(0, 0, 0));
        naslovpnl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 6));

        naslovlbl.setFont(new java.awt.Font("Tahoma", 1, 60)); // NOI18N
        naslovlbl.setForeground(new java.awt.Color(240, 240, 240));
        naslovlbl.setText("TURISTIČKA AGENCIJA FALCON");

        javax.swing.GroupLayout naslovpnlLayout = new javax.swing.GroupLayout(naslovpnl);
        naslovpnl.setLayout(naslovpnlLayout);
        naslovpnlLayout.setHorizontalGroup(
            naslovpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(naslovpnlLayout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(naslovlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 992, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(126, Short.MAX_VALUE))
        );
        naslovpnlLayout.setVerticalGroup(
            naslovpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(naslovpnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(naslovlbl, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(naslovpnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1280, -1));

        gostpnl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        gostpnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        emaillbl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        emaillbl.setText("Email");
        gostpnl.add(emaillbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 130, 30));

        imelbl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        imelbl.setText("Ime");
        gostpnl.add(imelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 130, 30));

        prezimelbl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        prezimelbl.setText("Prezime");
        gostpnl.add(prezimelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 130, 30));

        adresalbl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        adresalbl.setText("Adresa");
        gostpnl.add(adresalbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 130, 30));

        telefonlbl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        telefonlbl.setText("Telefon");
        gostpnl.add(telefonlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 130, 30));

        emailfld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailfldActionPerformed(evt);
            }
        });
        gostpnl.add(emailfld, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 220, 30));

        imefld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imefldActionPerformed(evt);
            }
        });
        gostpnl.add(imefld, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 220, 30));

        prezimefld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prezimefldActionPerformed(evt);
            }
        });
        gostpnl.add(prezimefld, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 220, 30));

        adresafld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adresafldActionPerformed(evt);
            }
        });
        gostpnl.add(adresafld, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 220, 30));

        telefonfld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefonfldActionPerformed(evt);
            }
        });
        gostpnl.add(telefonfld, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 220, 30));

        dodajbtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        dodajbtn.setText("Dodaj");
        dodajbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dodajbtnActionPerformed(evt);
            }
        });
        gostpnl.add(dodajbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 160, 40));

        getContentPane().add(gostpnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 430, 270));

        detaljipnl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        detaljipnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        polazaklbl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        polazaklbl.setText("Destinacija");
        detaljipnl.add(polazaklbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 140, 30));

        polazaklbl1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        polazaklbl1.setText("Polazak");
        detaljipnl.add(polazaklbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 140, 30));

        destinacijacbx.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        destinacijacbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Izaberite", "Madrid", "Rim", "Pariz", " ", " " }));
        destinacijacbx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destinacijacbxActionPerformed(evt);
            }
        });
        detaljipnl.add(destinacijacbx, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 130, -1));

        polazakcbx.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        polazakcbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Izaberite", "Beograd", "Nis\t" }));
        polazakcbx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                polazakcbxActionPerformed(evt);
            }
        });
        detaljipnl.add(polazakcbx, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 130, -1));

        prtljagbox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        prtljagbox.setText("Prtljag");
        detaljipnl.add(prtljagbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, -1, -1));

        taksebox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        taksebox.setText("Takse");
        detaljipnl.add(taksebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        osiguranjebox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        osiguranjebox.setText("Osiguranje");
        detaljipnl.add(osiguranjebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, -1, -1));

        getContentPane().add(detaljipnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 130, 370, 270));

        detalji2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        detalji2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        letlbl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        letlbl.setText("Let");
        detalji2.add(letlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 110, -1));

        pklasarb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pklasarb.setText("Prva klasa");
        detalji2.add(pklasarb, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        eklasarb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        eklasarb.setText("Ekonomska klasa");
        detalji2.add(eklasarb, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        bklasarb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bklasarb.setText("Biznis klasa");
        detalji2.add(bklasarb, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        kartalbl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        kartalbl.setText("Karta");
        detalji2.add(kartalbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 80, -1));

        povratnarb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        povratnarb.setText("Povratna");
        detalji2.add(povratnarb, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 110, -1));

        jednosmernarb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jednosmernarb.setText("Jednosmerna");
        detalji2.add(jednosmernarb, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, -1, -1));

        getContentPane().add(detalji2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 430, 210));

        cenepnl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        cenepnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ukupnolbl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ukupnolbl.setText("Ukupno");
        cenepnl.add(ukupnolbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 100, -1));

        cenalbl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        cenalbl.setText("Cena");
        cenepnl.add(cenalbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 100, -1));

        takselbl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        takselbl.setText("Takse");
        cenepnl.add(takselbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 100, -1));

        cena3lbl.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        cena3lbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        cenepnl.add(cena3lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 160, 30));

        cena1lbl.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        cena1lbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        cenepnl.add(cena1lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 14, 160, 30));

        cena2lbl.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        cena2lbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        cenepnl.add(cena2lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 160, 30));

        getContentPane().add(cenepnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 410, 370, 130));

        racunpnl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        racunpnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        racunlbl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        racunlbl.setText("Račun");
        racunpnl.add(racunlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 90, 30));

        racunarea.setColumns(20);
        racunarea.setRows(5);
        jScrollPane1.setViewportView(racunarea);

        racunpnl.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 360, 360));

        getContentPane().add(racunpnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 130, 400, 410));

        dugmadpnl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        dugmadpnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        izlazbtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        izlazbtn.setText("IZLAZ");
        izlazbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                izlazbtnActionPerformed(evt);
            }
        });
        dugmadpnl.add(izlazbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, 160, 50));

        racunbtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        racunbtn.setText("RAČUN");
        racunbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                racunbtnActionPerformed(evt);
            }
        });
        dugmadpnl.add(racunbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 160, 50));

        ponistibtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ponistibtn.setText("PONIŠTI");
        ponistibtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ponistibtnActionPerformed(evt);
            }
        });
        dugmadpnl.add(ponistibtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 160, 50));

        ukupnobtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ukupnobtn.setText("UKUPNO");
        ukupnobtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ukupnobtnMouseClicked(evt);
            }
        });
        dugmadpnl.add(ukupnobtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 160, 50));

        getContentPane().add(dugmadpnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 550, 800, 70));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void emailfldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailfldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailfldActionPerformed

    private void imefldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imefldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_imefldActionPerformed

    private void prezimefldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prezimefldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prezimefldActionPerformed

    private void adresafldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adresafldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adresafldActionPerformed

    private void telefonfldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefonfldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefonfldActionPerformed

    private void destinacijacbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destinacijacbxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_destinacijacbxActionPerformed

    private void polazakcbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_polazakcbxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_polazakcbxActionPerformed
    private JFrame frame;
    private void izlazbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_izlazbtnActionPerformed
        
        frame = new JFrame("Izlaz");
				if(JOptionPane.showConfirmDialog(frame, "Da li zelite da izadjete ? ","Turisticka agencija FX", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION) {
					System.exit(0);
				
			}
    }//GEN-LAST:event_izlazbtnActionPerformed

    private void ponistibtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ponistibtnActionPerformed
       
        imefld.setText(null);
        prezimefld.setText(null);
        adresafld.setText(null);
        telefonfld.setText(null);
        emailfld.setText(null);
        cena1lbl.setText(null);
        cena2lbl.setText(null);
        cena3lbl.setText(null);
        eklasarb.setSelected(false);
        bklasarb.setSelected(false);
        pklasarb.setSelected(false);
        jednosmernarb.setSelected(false);
        povratnarb.setSelected(false);
        polazakcbx.setSelectedItem("Izaberite");
        destinacijacbx.setSelectedItem("Izaberite");
        taksebox.setSelected(false);
        osiguranjebox.setSelected(false);
        prtljagbox.setSelected(false);
        racunarea.setText(null);
        
        
    }//GEN-LAST:event_ponistibtnActionPerformed

    private void racunbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_racunbtnActionPerformed

        Calendar kalendar = Calendar.getInstance();
        kalendar.getTime();
        
        SimpleDateFormat vreme= new SimpleDateFormat("HH:mm:ss");
        String sat = (vreme.format(kalendar.getTime()));
        
        SimpleDateFormat datum = new SimpleDateFormat("dd:MM:yyyy");
        String datum2 = (datum.format(kalendar.getTime()));
        
        int br;
        String brrac="";
        br = 424 +(int) (Math.random()* 645);
        brrac += br +424;
        
        String ime = imefld.getText();
        String prezime = prezimefld.getText();
        String adresa = adresafld.getText();
        String telefon = telefonfld.getText();
        String email = emailfld.getText();
        String cena = cena1lbl.getText();
        String takse = cena2lbl.getText();
        String ukupno = cena3lbl.getText();
        
        racunarea.append("\tTuristicka agencija FX:\n\n"
				+"Broj racuna:\t\t" + brrac
				+"\n*********************************************************************************************"
				+ "\nIme:\t\t" + ime
				+"\nPrezime:\t\t" + prezime
				+"\nAdresa:\t\t" + adresa
				+"\nTelefon:\t\t" + telefon
				+"\nEmail:\t\t" + email
				+"\nCena:\t\t" +cena
				+"\nTakse:\t\t" + takse
				+"\nUkupno:\t\t" + ukupno
				+"\n*********************************************************************************************"
				+"\nDatum:" + datum2 + "\tVreme:" + sat
				+"\n\n\tTuristicka agencija FX");    
        
    }//GEN-LAST:event_racunbtnActionPerformed

    private void dodajbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dodajbtnActionPerformed
        
        try{
            theQuery("insert "
                    + "into gosti (ime,prezime,adresa,telefon,email) values "
                    + "('"+imefld.getText()+"', '"+prezimefld.getText()+"', "
                            + "'"+adresafld.getText()+"', '"+telefonfld.getText()+"', '"+emailfld.getText()+"')");
        }
        catch(Exception Ex){
            
        }
    }//GEN-LAST:event_dodajbtnActionPerformed
        
        double madrid = 320;
        double rim = 280;
        double pariz = 360;
        double eko = 60;
        double biz = 90;
        double prva = 100;
        double jednosm = 60;
        double povr = 120;
        double takse = 43.50;
        double osig = 10.30;
        double prtljag = 5.75;
        
    private void ukupnobtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ukupnobtnMouseClicked
        
       
        
        if((destinacijacbx.getSelectedItem().equals("Madrid"))&& eklasarb.isSelected()&& 
                jednosmernarb.isSelected() && taksebox.isSelected()){
            
            double cena= madrid + eko + jednosm;
            String polje1 = String.format("$%.2f", cena);
            cena1lbl.setText(polje1);
            String tax = String.format("$%.2f", takse);
            cena2lbl.setText(tax);
            double polje2 = cena + takse;
            String ukupno = String.format("$%.2f", polje2);
            cena3lbl.setText(ukupno);
            
        }
        if (destinacijacbx.getSelectedItem().equals("Madrid") && eklasarb.isSelected() 
                && jednosmernarb.isSelected() && taksebox.isSelected() && osiguranjebox.isSelected()&& prtljagbox.isSelected()){
            
            double cen1 = madrid + eko + jednosm;
            String a = String.format("$%.2f", cen1);
            cena1lbl.setText(a);
            double cen2 = takse + osig + prtljag;
            String b = String.format("$%.2f", cen2);
            cena2lbl.setText(b);
            double cen3 = cen1 + cen2;
            String c = String.format("$%.2f", cen3);
            cena3lbl.setText(c);
            
        }
        if(destinacijacbx.getSelectedItem().equals("Madrid") && bklasarb.isSelected() && povratnarb.isSelected()
                && taksebox.isSelected() && osiguranjebox.isSelected()){
         
            double c1 = madrid + biz + povr;
            String d = String.format("$%.2f", c1);
            cena1lbl.setText(d);
            double c2 = takse + osig;
            String e = String.format("$%.2f", c2);
            cena2lbl.setText(e);
            double c3 = c1 + c2;
            String f = String.format("$%.2f", c3);
            cena3lbl.setText(f);
        }
        
        if(destinacijacbx.getSelectedItem().equals("Madrid") && bklasarb.isSelected() && jednosmernarb.isSelected()
                && taksebox.isSelected() && osiguranjebox.isSelected() && prtljagbox.isSelected()){
            
            double pon1 = madrid + biz + jednosm;
            String d1 = String.format("$%.2f", pon1);
            cena1lbl.setText(d1);
            double pon2 = takse + osig + prtljag;
            String d2 = String.format("$%.2f", pon2);
            cena2lbl.setText(d2);
            double pon3 = pon1 + pon2;
            String d3 = String.format("$%.2f", pon3);
            cena3lbl.setText(d3);
        }
        
        if(destinacijacbx.getSelectedItem().equals("Madrid") && pklasarb.isSelected() && jednosmernarb.isSelected() 
                && taksebox.isSelected() && osiguranjebox.isSelected() && prtljagbox.isSelected()){
           
            double ce1 = madrid + prva + jednosm;
            String g = String.format("$%.2f", ce1);
            cena1lbl.setText(g);
            double ce2 = takse + osig + prtljag;
            String h = String.format("$%.2f", ce2);
            cena2lbl.setText(h);
            double ce3 = ce1 + ce2;
            String i = String.format("$%.2f", ce3);
            cena3lbl.setText(i);
        }
        
        if(destinacijacbx.getSelectedItem().equals("Madrid") && pklasarb.isSelected() && povratnarb.isSelected() && taksebox.isSelected()){
            
            double pe1 = madrid + prva + povr;
            String u1 = String.format("$%.2f", pe1);
            cena1lbl.setText(u1);
            String u2 = String.format("$%.2f", takse);
            cena2lbl.setText(u2);
            double pe3 = pe1 + takse;
            String u3 = String.format("$%.2f", pe3);
            cena3lbl.setText(u3);
            
        }
        if(destinacijacbx.getSelectedItem().equals("Rim") && eklasarb.isSelected() && jednosmernarb.isSelected() && taksebox.isSelected()){
            
            double m1 = rim + eko + jednosm;
            String b1 = String.format("$%.2f", m1);
            cena1lbl.setText(b1);
            String b2 = String.format("$%.2f", takse);
            cena2lbl.setText(b2);
            double m3 = m1 + takse;
            String b3 = String.format("$%.2f", m3);
            cena3lbl.setText(b3);
            
        }
        if(destinacijacbx.getSelectedItem().equals("Rim") &&  eklasarb.isSelected() && jednosmernarb.isSelected() && taksebox.isSelected()&&
                osiguranjebox.isSelected()&&prtljagbox.isSelected()){
            
            double n1 = rim + eko + jednosm;
            String o1 = String.format("$%.2f", n1);
            cena1lbl.setText(o1);
            double n2 = takse + osig + prtljag;
            String o2 = String.format("$%.2f", n2);
            cena2lbl.setText(o2);
            double n3 = n1 + n2;
            String o3 = String.format("$%.2f", n3);
            cena3lbl.setText(o3);
        }
        if(destinacijacbx.getSelectedItem().equals("Rim")&& bklasarb.isSelected() && povratnarb.isSelected() && taksebox.isSelected() && osiguranjebox.isSelected()){
        
            double z1 = rim + biz + povr;
            String x1 =String.format("$%.2f", z1);
            cena1lbl.setText(x1);
            double z2 = takse + osig;
            String x2 = String.format("$%.2f", z2);
            cena2lbl.setText(x2);
            double z3 = z1 + z2;
            String x3 = String.format("$%.2f", z3);
            cena3lbl.setText(x3);
        }
        if(destinacijacbx.getSelectedItem().equals("Rim") && bklasarb.isSelected() 
                && jednosmernarb.isSelected()&& taksebox.isSelected() && osiguranjebox.isSelected() && prtljagbox.isSelected()){
            
            double k1 = rim + biz + jednosm;
            String l1= String.format("$%.2f", k1);
            cena1lbl.setText(l1);
            double k2 = takse + osig + prtljag;
            String l2 = String.format("$%.2f", k2);
            cena2lbl.setText(l2);
            double k3 = k1 + k2;
            String l3 =String.format("$%.2f", k3);
            cena3lbl.setText(l3);
        }
        if(destinacijacbx.getSelectedItem().equals("Rim") && pklasarb.isSelected() && jednosmernarb.isSelected() && taksebox.isSelected()){
        
            double f1 = rim + prva + jednosm;
            String rim1 = String.format("$%.2f", f1);
            cena1lbl.setText(rim1);
            String rim2 = String.format("$%.2f", takse);
            cena2lbl.setText(rim2);
            double f3 = f1 + takse;
            String rim3 = String.format("$%.2f", f3);
            cena3lbl.setText(rim3);
        }
        if(destinacijacbx.getSelectedItem().equals("Rim") && pklasarb.isSelected() && povratnarb.isSelected() 
                && taksebox.isSelected() && osiguranjebox.isSelected() &&  prtljagbox.isSelected()){
            
            double g1 = rim + prva + povr;
            String italija1 = String.format("$%.2f", g1);
            cena1lbl.setText(italija1);
            double g2 = takse + osig + prtljag;
            String italija2 = String.format("$%.2f", g2);
            cena2lbl.setText(italija2);
            double g3 = g1 + g2;
            String italija3 =String.format("$%.2f", g3);
            cena3lbl.setText(italija3);
        }
        
       
        if(destinacijacbx.getSelectedItem().equals("Madrid") && pklasarb.isSelected()&& povratnarb.isSelected() 
                && taksebox.isSelected() && osiguranjebox.isSelected() &&  prtljagbox.isSelected()){
            
            double spa1 = madrid + prva + povr;
            String mad1 = String.format("$%.2f", spa1);
            cena1lbl.setText(mad1);
            double spa2 = takse + osig + prtljag;
            String mad2 = String.format("$%.2f", spa2);
            cena2lbl.setText(mad2);
            double spa3 = spa1 + spa2;
            String mad3 = String.format("$%.2f", spa3);
            cena3lbl.setText(mad3);
        }
        if(destinacijacbx.getSelectedItem().equals("Pariz") && eklasarb.isSelected() && jednosmernarb.isSelected() 
                && taksebox.isSelected() && osiguranjebox.isSelected() && prtljagbox.isSelected()){
            
            double fra1 = pariz + eko + jednosm;
            String par1 = String.format("$%.2f", fra1);
            cena1lbl.setText(par1);
            double fra2 = takse + osig +  prtljag;
            String par2 = String.format("$%.2f", fra2);
            cena2lbl.setText(par2);
            double fra3 = fra1 + fra2;
            String par3 = String.format("$%.2f", fra3);
            cena3lbl.setText(par3);
        }
        if(destinacijacbx.getSelectedItem().equals("Pariz") && eklasarb.isSelected() && jednosmernarb.isSelected() && taksebox.isSelected()){
        
            double france1 = pariz + eko + jednosm;
            String pariz1 = String.format("$%.2f", france1);
            cena1lbl.setText(pariz1);
            String pariz2 = String.format("$%.2f", takse);
            cena2lbl.setText(pariz2);
            double france3 = france1 + takse;
            String pariz3 = String.format("$%.2f", france3);
            cena3lbl.setText(pariz3);  
        }
        if(destinacijacbx.getSelectedItem().equals("Pariz") && bklasarb.isSelected() && povratnarb.isSelected() 
                && taksebox.isSelected() && osiguranjebox.isSelected() && prtljagbox.isSelected()){
            
            double bklasa1 = pariz + biz + povr;
            String karta1 = String.format("$%.2f", bklasa1);
            cena1lbl.setText(karta1);
            double bklasa2 = takse + osig + prtljag;
            String karta2 = String.format("$%.2f", bklasa2);
            cena2lbl.setText(karta2);
            double bklasa3 = bklasa1 + bklasa2;
            String karta3 = String.format("$%.2f", bklasa3);
            cena3lbl.setText(karta3);
        }
        if(destinacijacbx.getSelectedItem().equals("Pariz") && bklasarb.isSelected() && jednosmernarb.isSelected() 
                && taksebox.isSelected() && osiguranjebox.isSelected() && prtljagbox.isSelected()){
            
            double put1 = pariz + biz + jednosm;
            String ceh1 = String.format("$%.2f", put1);
            cena1lbl.setText(ceh1);
            double put2 = takse + osig + prtljag;
            String ceh2 = String.format("$%.2f", put2);
            cena2lbl.setText(ceh2);
            double put3 = put1 + put2;
            String ceh3 = String.format("$%.2f", put3);
            cena3lbl.setText(ceh3);
        }
        if(destinacijacbx.getSelectedItem().equals("Pariz") && pklasarb.isSelected() 
                && jednosmernarb.isSelected() && taksebox.isSelected() && osiguranjebox.isSelected() && prtljagbox.isSelected()){
            
            double ponuda1 = pariz + prva + jednosm;
            String traznja1 = String.format("$%.2f", ponuda1);
            cena1lbl.setText(traznja1);
            double ponuda2 = takse + osig + prtljag;
            String traznja2 = String.format("$%.2f", ponuda2);
            cena2lbl.setText(traznja2);
            double ponuda3 = ponuda1 + ponuda2;
            String traznja3 = String.format("$%.2f", ponuda3);
            cena3lbl.setText(traznja3);
        
        }
        if(destinacijacbx.getSelectedItem().equals("Pariz") && pklasarb.isSelected() 
                && povratnarb.isSelected() && taksebox.isSelected() && osiguranjebox.isSelected()){
            
            double leto1 = pariz + prva + povr;
            String zima1 = String.format("$%.2f", leto1);
            cena1lbl.setText(zima1);
            double leto2 = takse + osig;
            String zima2 = String.format("$%.2f", leto2);
            cena2lbl.setText(zima2);
            double leto3 = leto1 + leto2;
            String zima3 = String.format("$%.2f", leto3);
            cena3lbl.setText(zima3);
        }
        
      
    }//GEN-LAST:event_ukupnobtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agencija.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agencija.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agencija.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agencija.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Agencija().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adresafld;
    private javax.swing.JLabel adresalbl;
    private javax.swing.JRadioButton bklasarb;
    private javax.swing.JLabel cena1lbl;
    private javax.swing.JLabel cena2lbl;
    private javax.swing.JLabel cena3lbl;
    private javax.swing.JLabel cenalbl;
    private javax.swing.JPanel cenepnl;
    private javax.swing.JComboBox<String> destinacijacbx;
    private javax.swing.JPanel detalji2;
    private javax.swing.JPanel detaljipnl;
    private javax.swing.JButton dodajbtn;
    private javax.swing.JPanel dugmadpnl;
    private javax.swing.JRadioButton eklasarb;
    private javax.swing.JTextField emailfld;
    private javax.swing.JLabel emaillbl;
    private javax.swing.JPanel gostpnl;
    private javax.swing.JTextField imefld;
    private javax.swing.JLabel imelbl;
    private javax.swing.JButton izlazbtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton jednosmernarb;
    private javax.swing.JLabel kartalbl;
    private javax.swing.JLabel letlbl;
    private javax.swing.JLabel naslovlbl;
    private javax.swing.JPanel naslovpnl;
    private javax.swing.JCheckBox osiguranjebox;
    private javax.swing.JRadioButton pklasarb;
    private javax.swing.JComboBox<String> polazakcbx;
    private javax.swing.JLabel polazaklbl;
    private javax.swing.JLabel polazaklbl1;
    private javax.swing.JButton ponistibtn;
    private javax.swing.JRadioButton povratnarb;
    private javax.swing.JTextField prezimefld;
    private javax.swing.JLabel prezimelbl;
    private javax.swing.JCheckBox prtljagbox;
    private javax.swing.JTextArea racunarea;
    private javax.swing.JButton racunbtn;
    private javax.swing.JLabel racunlbl;
    private javax.swing.JPanel racunpnl;
    private javax.swing.JCheckBox taksebox;
    private javax.swing.JLabel takselbl;
    private javax.swing.JTextField telefonfld;
    private javax.swing.JLabel telefonlbl;
    private javax.swing.JButton ukupnobtn;
    private javax.swing.JLabel ukupnolbl;
    // End of variables declaration//GEN-END:variables
}
